## 複数のcatch
ここでは、複数のcatchについて説明していきます。

### 目次
* [複数のcatch](#sec1)

### <a name="sec1"></a>複数のcatch
例外が発生する可能性のある文に対して、複数例外が発生する可能性がある場合は、try-catchの文においてcatchを複数記述する必要があります。

また、発生した例外をcatchブロックでキャッチする場合、キャッチする例外クラスの親クラスでも例外をキャッチすることが可能です。  
ただし、発生した例外毎に適切な対処が必要な場合は発生する例外毎に記述しなければいけません。

```java
public class Sample6_3 {
	public static void main(String[] args) {
		int[] x = {0,1,2,3,4,};
		try {
			System.out.println("x[6] :" + x[6]);
			System.out.println("x[3] :" + x[3]);
		} catch(ArithmeticException ae) {
			System.out.println("An arithmetic exception occurred");
		} catch(ArrayIndexOutOfBoundsException oe) {
			System.out.println("Array index out of bound! ");
		} catch(IndexOutOfBoundsException ie) {
			System.out.println("Some kind of index out of bound!");
		} finally {
			System.out.println("finally block must be executed!");
		}
		System.out.println("x[0] :" + x[0]);
	}
}
```

このように例外毎にcatchブロックを作成して例外処理を追加することが可能です。  
では、このサンプルアプリケーションを親クラスを追加して例外処理をさせてみましょう。

