## throwsキーワード
ここでは、throwsキーワードについて説明していきます。

### 目次
* [throwsとは](#sec1)
* [throwsの使用例](#sec2)

### <a name="sec1"></a>throwsとは
プログラムの中では、各メソッドの中でそれぞれ例外処理を記述するのではなく、メソッドの呼び出し元に例外処理を任すことができます。  
その際に使用するキーワードが「throws」です。

thwosの構文は以下になります。

```sh
<修飾子> <戻り値の型> <メソッド名>(引数リスト) throws <例外クラス1>, <例外クラス2> {
	// ここにコードを記入
}
```

上記のとおり、メソッド内の処理によって複数の例外が発生する可能性があれば、throwsキーワードの後にクラス名をカンマで区切って記述します。  

以下はthrowsキーワードを使用したサンプルプログラムになります。

```java
import java.io.IOException;

public class Sample6_4_2 {
	public static void main(String[] args) {
		calledMethod();
	}
	
	static void calledMethod() throws IOException {
		throw new IOException();
	}
}
```

calledMethodでthrowを使って意図的にエラーを発生させていますが、throwsキーワードを使用して呼び出し元へ例外処理をゆだねています。
そのため、この例ではコンパイルエラーとなります。  
今回の場合では、mainメソッド内でtry-catch文で囲むか、mainメソッドにthrowsを追加する必要があります。

▼throwsとtry-catchの2通りある理由  
[https://qiita.com/shunsuke227ono/items/18059198777812e446b4](https://qiita.com/shunsuke227ono/items/18059198777812e446b4)